server:
  port: 9999
spring:
  application:
    name: jpa
  profiles:
    active: local
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        use_sql_comments: true
        format_sql: true